### ISSUE TITLE
How would a conclusion look like?

### ISSUE THREAD

**Issue by plonerma** [plonerma/understanding-maml#13]
- [x] Futher readings
- [x] Refer to code again
- [x] short conclusion
- [x] ~Make maml-tf2 repository public~

**Comment by plonerma** [comment]
PR #14 contains a starting point

**Comment by luis-mueller** [comment]
Conclusion via b377133951b653faf52e92ea3f4b631338002463

**Comment by luis-mueller** [comment]
Making maml-tf2 public depends heavily on #11, maybe we should just close this one and move the maml-tf2 stuff together into #11?

**Comment by plonerma** [comment]
I added the task to #11 
One thing I would also like to add to the comparison, is an empirical comparison (ie. accuracy numbers on omniglot and mini-imagenet as reported in the papers).
I will close this issue once Im done with that.

**Comment by plonerma** [comment]
> Before you leave: After letting your browser compute a bunch of meta-updates, you may want to cool it off and take a look at our computationally lightweight but not-to-miss further reading section. 

Top-notch transition by the way! I like it :smile:

**Comment by luis-mueller** [comment]
> One thing I would also like to add to the comparison, is an empirical comparison (ie. accuracy numbers on omniglot and mini-imagenet as reported in the papers).

Do you want to add screenshots or build your own table?

**Comment by plonerma** [comment]
I will just translate it into html. One method (MAML, FOMAML, REPTILE, iMAML) per row, and one or two columns per task. I will use the results from the papers though.

**Comment by plonerma** [comment]
I think this might integrate nicer then a screenshot

**Comment by plonerma** [comment]
Before we didn't include empirical results, which (in my opinion) is actually good, since we are focusing on the theory. But I think it would be nice to show at the end: the methods are different, but all produce reasonably good results...

=> That might also be a good justification of why we even cover all of them: there is no clear winner.

**Comment by plonerma** [comment]
Empricial results added in 052fdcf35f7290b2207e268f7b8ca9f82b543827
