### ISSUE TITLE
(Static) Plots for "Why pretrained doesn't work"

### ISSUE THREAD

**Issue by luis-mueller** [plonerma/understanding-maml#21]
- [x] task loss spaces on top
- [x] meta loss space for 0 steps (aka sum)
- [x] meta loss space for n > 0 steps (aka maml)

Optional
- [x] possible to increase steps dynamically (svgs/contours)

**Comment by plonerma** [comment]
Static contour SVGs + notebook can be found in `public/img/static_contours/`

**Comment by plonerma** [comment]
Implemented most of it.

- [ ] Validate python implementation
- [x] Write explanation (figcaption)
- [x] Remove twoTasks component
- [x] Try out smaller step size and more steps

**Comment by plonerma** [comment]
While scrolling towards a higher number of steps, the loss generally gets lower (this is also visiible by the movement of the iso lines: first they move outside and at some point new thresholds are used and they jump back). It might make sense to keep the thresholds constant throughout the steps. The downside is that the plot will entirely fill with the darkest color at some point.

**Comment by plonerma** [comment]
Just tried it out: There is not much left to see after only a few steps.

**Comment by luis-mueller** [comment]
First of all, just checked it out and it looks great! Generally I'd say the point comes across, which is the main part of it. Now, the visuals are nice and unless what is displayed is very off (which is suppose it isn't) - we are good.
