### ISSUE TITLE
Own section for First-Order Methods

### ISSUE THREAD

**Issue by luis-mueller** [plonerma/understanding-maml#26]
Currently when navigating to FOMAML we arrive at "First-Order Methods: Why differentiating through an optimizer is actually as complicated as it sounds". Suggestion. In the menu, instead of the "variants", we write:

"Variants: First-Order Methods"

and then make it a link that jumps to the top of the page. Then clicking on FOMAML in the menu sends one directly to the FOMAML part!

**Comment by plonerma** [comment]
Would "Variants: First-Order Methods" still be the section title in the toc of all variants? iMAML is not a First-Order method that might be misleading...

**Comment by plonerma** [comment]
Im not sure what the best approach would be here - FOMAML could certainly be a page of its own, but "First-Order Methods: Why differentiating through" not (yet).

Maybe just adding another menuitem under variants (e.g. "intro to first order-variants") might suffice?

Alternatively, we might make it its own page and add a bit more text around it: We could then alsoo  include the broader argument, of why a large number of steps in MAML is problematic and then treat it as the general introduction to the variants (this might be a little bit more time intensive though).

**Comment by plonerma** [comment]
> We will now spend some time on introducing the **two** most prominent solutions to this problem, as well as comparing them to MAML and to each other.

This should also be three (before I change that we may want to decide how to go on - Im just leaving this here as a reminder for myself).

**Comment by luis-mueller** [comment]
I'd say we go with "Intro to first order-variants" under the variants but leave it on the fomaml page. We could further consider to put reptile also on that page to get the first-order stuff together.

**Comment by plonerma** [comment]
Ok, then lets discuss it today maybe. I think I actually like the seperate page idea since that would allow us to shed some light on the downsides of MAML which also motivate iMAML.

**Comment by luis-mueller** [comment]
Solved by #27
