### ISSUE TITLE
Comparison of methods

### ISSUE THREAD

**Issue by plonerma** [plonerma/understanding-maml#7]
- [x] Introduction still valid?
- [x] connect sliders
- [x] figure out integrate into the article / single page web app
- [x] loss space?
- [x] add empirical results (omniglot & mini-imagenet)
- [x] Allow user to switch between loss spaces

**Comment by luis-mueller** [comment]
Im working on them sliders!

**Comment by plonerma** [comment]
052fdcf35f7290b2207e268f7b8ca9f82b543827

**Comment by luis-mueller** [comment]
Awesome, so now we just have to discuss what we do with the webapp. Wanna check it out (my latest commit) and tell me what you think? I added a toggle for activating the methods to maybe just compare two at a time or so...

Is the reg. coeff. of iMAML aleady implemented in js? If yes, we should connect the slider. Didn't find the variable.

**Comment by luis-mueller** [comment]
Btw I suggest we just leave the webapp where it is and close this issue. It's not optimal because it overlaps but I don't know if it is better to put it on a standalone page.

**Comment by plonerma** [comment]
I will take a look (regarding the regularization parameter).

Yes, the way it is right now should be fine. Plus, this way it has some context (instead of being isolated).

I really like the visual effect of the disabled methods - makes it quite clear what is happening (at least for me, knowing what is about anyways...).

One last thing that we should add: Either their should be a dropdown box for the different tasks or we should make it clear that there is more than one.

**Comment by plonerma** [comment]
It would probably also be nicer if the sliders had equal length, but I'm not sure if there is an easy way to achieve this using the slider component I wrote...

**Comment by plonerma** [comment]
Have you noticed, there is a really weird behavior: only MAML will update, if it is solely active, and iMAML only updates, if all methods are active? Maybe there is something off with the filter...

**Comment by plonerma** [comment]
Ah, if maml is filtered away, all following `i`s reference the wrong alg.
Fixed in 6adcd8212bc10ac3180e7cf68e1af58ab6ef3f77

**Comment by luis-mueller** [comment]
ok awesome, so we keep the figure there for now and close this?

**Comment by plonerma** [comment]
I will work on this tomorrow:
- [x] Allow user to switch between loss spaces

and then close it.
